.\"
.\" Copyright (c) 2015-2016 Franco Fichtner <franco@opnsense.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd July 21, 2016
.Dt OPNSENSE-BOOTSTRAP 8
.Os
.Sh NAME
.Nm opnsense-bootstrap
.Nd OPNsense bootstrap utility
.Sh SYNOPSIS
.Nm
.Op Fl fy
.Op Fl n Ar flavour
.Op Fl t Ar type
.Op Fl V Ar version
.Nm
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility offers a way to reset a compatible system to the latest
available version of OPNsense.
It can be used to repair a broken system or transform a matching
.Fx
installation.
Compatibility with
.Fx
is subject to change and
.Ud .
.Pp
The options are as follows:
.Bl -tag -width ".Fl n Ar flavour" -offset indent
.It Fl f
Do a full factory reset, removing all previous OPNsense configuration
files.
.It Fl n Ar flavour
Change the package repository to
.Ar flavour .
Possible values are
.Sq LibreSSL
and
.Sq OpenSSL .
The default is
.Sq OpenSSL .
.It Fl t Ar type
Select the top package to be bootstrapped from the repository.
The default is
.Sq opnsense .
.It Fl V Ar version
Select a different major version target.
.It Fl v
Print the current version string.
.It Fl y
This option omits the confirmation prompt.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr opnsense-update 8
.Sh AUTHORS
.An Franco Fichtner Aq Mt franco@opnsense.org
