.\"
.\" Copyright (c) 2016-2017 Franco Fichtner <franco@opnsense.org>
.\" Copyright (c) 2017 Marco Woitschitzky <woi@posteo.de>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd September 5, 2017
.Dt OPNSENSE-REVERT 8
.Os
.Sh NAME
.Nm opnsense-revert
.Nd OPNsense revert utility
.Sh SYNOPSIS
.Nm
.Op Fl i
.Op Fl r Ar release
.Ar package ...
.Sh DESCRIPTION
The
.Nm
utility offers to securely install previous versions of packages found
in an OPNsense release as long as the selected mirror caches said release.
.Pp
The options are as follows:
.Bl -tag -width ".Fl r Ar release" -offset indent
.It Fl i
Ignore the signature verification result.
.It Fl r Ar release
Select the
.Ar release
of the package to be installed.
Note that the release is not the individual package version,
but rather the version found in said OPNsense release.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Revert unbound to the version found in OPNsense 17.7.1:
.Pp
.Dl # opnsense-revert -r 17.7.1 unbound
.Pp
Bring unbound back to the current version:
.Pp
.Dl # opnsense-revert unbound
.Pp
.Sh SEE ALSO
.Xr opnsense-update 8 ,
.Xr opnsense-verify 8
.Sh AUTHORS
.An Franco Fichtner Aq Mt franco@opnsense.org
